import { ZoomEntry } from './supabase'

export const MARCH_DATA: Omit<ZoomEntry, 'created_at'>[] = [
  {id:'m1',month:'March 2025',date:'3/2',rep:'Dan',company:'DAXX',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'m2',month:'March 2025',date:'3/3',rep:'Dan',company:'Gorilla Exteriors',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'m3',month:'March 2025',date:'3/3',rep:'Dan',company:'National Reliance Group',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Boris likes it, wants 5-10 commercial appts/mo'},
  {id:'m4',month:'March 2025',date:'3/3',rep:'Dan',company:'Major Roofing',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'m5',month:'March 2025',date:'3/4',rep:'Dan',company:'Lengacher Brothers',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Talking it over with brother/partner'},
  {id:'m6',month:'March 2025',date:'3/4',rep:'Dan',company:'AlphaOne Exteriors',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:'Rescheduled for next week'},
  {id:'m7',month:'March 2025',date:'3/5',rep:'Dan',company:'Apaxx',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:'Need to reschedule'},
  {id:'m8',month:'March 2025',date:'3/5',rep:'Dan',company:'Telge Roofing',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Zoom Thursday to discuss test kick off'},
  {id:'m9',month:'March 2025',date:'3/5',rep:'Dan',company:'Advanced Roofing',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Hesitant on pricing, meeting again next week'},
  {id:'m10',month:'March 2025',date:'3/6',rep:'Dan',company:'Texas Siding and Exteriors',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:'Missed Zoom'},
  {id:'m11',month:'March 2025',date:'3/2',rep:'Travis',company:'Champions Group Holdings',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Fetch-A-Tech hurting, could utilize our team'},
  {id:'m12',month:'March 2025',date:'3/2',rep:'Travis',company:'Fountain Comfort Group',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Going AI, will give us a shot'},
  {id:'m13',month:'March 2025',date:'3/3',rep:'Travis',company:'Socap Solar',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Interested in Speed-To-Lead'},
  {id:'m14',month:'March 2025',date:'3/3',rep:'Travis',company:'Cam Collective',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$31,500',notes:'35 Appointments @ $900 each'},
  {id:'m15',month:'March 2025',date:'3/4',rep:'Travis',company:'Tradewinds HVAC',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'m16',month:'March 2025',date:'3/4',rep:'Travis',company:'OnTrack Partners',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Sending updated deck, looking at opportunities'},
  {id:'m17',month:'March 2025',date:'3/3',rep:'Tim',company:'Hudson Physicians',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$31,250',notes:'Test 5k records @ $6.25, agreement by 3/16'},
  {id:'m18',month:'March 2025',date:'3/3',rep:'Tim',company:'GarageCo - Omaha Door',zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'$20,000',notes:'New client from equity group'},
  {id:'m19',month:'March 2025',date:'3/3',rep:'Tim',company:'Sunny Bliss Plumbing & Air',zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'$3,000',notes:'$3k/mo x 12 months'},
  {id:'m20',month:'March 2025',date:'3/4',rep:'Tim',company:'Fresh Air Duct Cleaning',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Follow up scheduled 3/10'},
  {id:'m21',month:'March 2025',date:'3/6',rep:'Tim',company:'Upfront Plumbing Drains Htg',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:'2nd zoom he has missed'},
  {id:'m22',month:'March 2025',date:'3/5',rep:'Mike',company:'PR Plumbing Heating Cooling',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Waiting for owner approval'},
  {id:'m23',month:'March 2025',date:'3/5',rep:'Mike',company:'Kelso Industries',zoom_type:'1st Zoom',sat:'Missed',outcome:'Not Interested',deal_value:'',notes:'Cancelled'},
  {id:'m24',month:'March 2025',date:'3/6',rep:'Mike',company:'Toro Construction',zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'$3,000',notes:''},
  {id:'m25',month:'March 2025',date:'3/10',rep:'Dan',company:'Horning Roofing',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Rescheduling'},
  {id:'m26',month:'March 2025',date:'3/10',rep:'Dan',company:'AlphaOne Exteriors',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Got stuck at a meeting'},
  {id:'m27',month:'March 2025',date:'3/11',rep:'Dan',company:'Lengacher Brothers',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Closed',deal_value:'$5,500',notes:'1 month test of 5 commercial'},
  {id:'m28',month:'March 2025',date:'3/11',rep:'Dan',company:'Redeemed Roofing Systems',zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'$5,500',notes:'5 commercial in KC'},
  {id:'m29',month:'March 2025',date:'3/12',rep:'Dan',company:'Ownerz Advocate Group',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Wants residential if hail hits'},
  {id:'m30',month:'March 2025',date:'3/12',rep:'Dan',company:'Hernandez Roofing',zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'$1,750',notes:'5 residential to start in KC'},
  {id:'m31',month:'March 2025',date:'3/12',rep:'Dan',company:'Telge Roofing',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Wants to do more research'},
  {id:'m32',month:'March 2025',date:'3/12',rep:'Dan',company:'Advanced Roofing + Sheet Metal',zoom_type:'3rd Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Capital budget maxed until July/Aug'},
  {id:'m33',month:'March 2025',date:'3/12',rep:'Dan',company:'Master Contractors',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:'No contact after multiple attempts'},
  {id:'m34',month:'March 2025',date:'3/13',rep:'Dan',company:'Nations Best Roofing',zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'$3,500',notes:'10 residential in OKC to start'},
  {id:'m35',month:'March 2025',date:'3/13',rep:'Dan',company:'Above Quality Roofing',zoom_type:'1st Zoom',sat:'Sat',outcome:'Not Interested',deal_value:'',notes:'Working with another company'},
  {id:'m36',month:'March 2025',date:'3/13',rep:'Dan',company:'Nations Roof',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Wants 15 storm + 15 retail commercial'},
  {id:'m37',month:'March 2025',date:'3/13',rep:'Dan',company:'Express Roofing LLC',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Storm, had to reschedule'},
  {id:'m38',month:'March 2025',date:'3/13',rep:'Dan',company:'Advanced Roofing Team Construction',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'',notes:'Looking to do 5 res and 5 comm'},
  {id:'m39',month:'March 2025',date:'3/9',rep:'Tim',company:'All Star AC Plumbing & Electrical',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$4,500',notes:'12 month plan, zoom 3/18'},
  {id:'m40',month:'March 2025',date:'3/10',rep:'Tim',company:'Proud Pops',zoom_type:'2nd Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'$6,000',notes:'1 month trial into partner plan'},
  {id:'m41',month:'March 2025',date:'3/10',rep:'Tim',company:'Fresh Air Duct Cleaning',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Closed',deal_value:'$12,000',notes:'2k records, 1 month'},
  {id:'m42',month:'March 2025',date:'3/11',rep:'Tim',company:'Roto-Rooter',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Wants commercial cold calling, send one pager'},
  {id:'m43',month:'March 2025',date:'3/12',rep:'Tim',company:'Chill-Brothers',zoom_type:'Follow-Up',sat:'Sat',outcome:'Closed',deal_value:'$12,000',notes:'$12k/mo for 3 months'},
  {id:'m44',month:'March 2025',date:'3/12',rep:'Tim',company:'Profitability Partners',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Wants to start with TX plumbing company'},
  {id:'m45',month:'March 2025',date:'3/13',rep:'Tim',company:'American Residential Services',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Avoca x Elite Call collab, speed to lead test'},
  {id:'m46',month:'March 2025',date:'3/10',rep:'Ryan',company:'Right Roofing',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Spoke 3/16, hiring internally'},
  {id:'m47',month:'March 2025',date:'3/11',rep:'Travis',company:'Elevate Franchise Brands',zoom_type:'2nd Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Missed Zoom'},
  {id:'m48',month:'March 2025',date:'3/11',rep:'Travis',company:'Enercare',zoom_type:'Follow-Up',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Need Legal Approval'},
  {id:'m49',month:'March 2025',date:'3/11',rep:'Andrew',company:'House Doctors',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Waiting for ST to HCP transfer, ~2600 customers'},
  {id:'m50',month:'March 2025',date:'3/16',rep:'Dan',company:'Regional Roofing',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:''},
  {id:'m51',month:'March 2025',date:'3/16',rep:'Dan',company:'Ownerz Advocate Group',zoom_type:'2nd Zoom',sat:'Missed',outcome:'Not Interested',deal_value:'',notes:'Wanted appts for new land'},
  {id:'m52',month:'March 2025',date:'3/16',rep:'Dan',company:'Health Compass Consulting',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$15,000',notes:'15 B2B appointments @ $1k each'},
  {id:'m53',month:'March 2025',date:'3/16',rep:'Dan',company:'Top Hat Chimney & Roofing',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Closed',deal_value:'$3,500',notes:'10 residential storm appts'},
  {id:'m54',month:'March 2025',date:'3/16',rep:'Dan',company:'Texas Siding and Exteriors',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:''},
  {id:'m55',month:'March 2025',date:'3/16',rep:'Travis',company:'Champions Group Holdings',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$18,000+',notes:'Sending Fetch-A-Tech data, SWAN next week'},
  {id:'m56',month:'March 2025',date:'3/16',rep:'Tim',company:'MR Electric',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Complete startup, needs license'},
  {id:'m57',month:'March 2025',date:'3/16',rep:'Tim',company:'Palms Garage Doors',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$4,125',notes:'2nd zoom Thursday @ 11am EST'},
  {id:'m58',month:'March 2025',date:'3/16',rep:'Ryan',company:'Star Accept Payment Solutions',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$5,000',notes:'5 appointments @ $1000 for 3 months'},
  {id:'m59',month:'March 2025',date:'3/17',rep:'Travis',company:'Independent Home',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$20,000+',notes:'Looking at other platforms, zoom 3/31'},
  {id:'m60',month:'March 2025',date:'3/17',rep:'Travis',company:'Glass Doctor - Ohio',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$10,000+',notes:'Zoom 3/24 @ 11:30AM CST'},
  {id:'m61',month:'March 2025',date:'3/17',rep:'Travis',company:'Neal Roofing',zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'$16,250',notes:'Dead lead dialing + cold calling'},
  {id:'m62',month:'March 2025',date:'3/17',rep:'Travis',company:'Turnpoint',zoom_type:'Discovery',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$20,000+',notes:'Meeting with new CMO Thursday'},
  {id:'m63',month:'March 2025',date:'3/17',rep:'Dan',company:'Gorilla Exteriors',zoom_type:'2nd Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Very busy with the storm'},
  {id:'m64',month:'March 2025',date:'3/18',rep:'Travis',company:'Valor Exterior Partners',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$10,000+',notes:'Jake speaking with leadership, VP Sales = Brian'},
  {id:'m65',month:'March 2025',date:'3/18',rep:'Dan',company:'Nations Roof',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$20,000',notes:'Sending jotform for 20-30 commercial appts'},
  {id:'m66',month:'March 2025',date:'3/19',rep:'Travis',company:'Roman Air',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'$12,000+',notes:'Ramon went home sick'},
  {id:'m67',month:'March 2025',date:'3/19',rep:'Travis',company:'Garage Door Grunts',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'$12,000+',notes:'Missed Zoom'},
  {id:'m68',month:'March 2025',date:'3/19',rep:'Travis',company:'Revive Home Remodeling',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Sent pricing for database dialing'},
  {id:'m69',month:'March 2025',date:'3/19',rep:'Tim',company:'Draven Construction',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$4,500',notes:'Call back, send recordings and numbers'},
  {id:'m70',month:'March 2025',date:'3/19',rep:'Tim',company:'All Star AC Plumbing & Electrical',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Closed',deal_value:'$4,500',notes:'12 month partner plan signed'},
  {id:'m71',month:'March 2025',date:'3/19',rep:'Dan',company:'Horning Roofing',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'',notes:'Interested in 8 commercial appts'},
  {id:'m72',month:'March 2025',date:'3/19',rep:'Andrew',company:'ProLift Garage Door',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$6,000+',notes:'Zoom 3/27 11AM CST, 60+ locations'},
  {id:'m73',month:'March 2025',date:'3/19',rep:'Tim',company:'Hudson Physicians',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$31,250',notes:'Waiting for Jotform'},
  {id:'m74',month:'March 2025',date:'3/19',rep:'Tim',company:'Aire Serv of Palm Desert',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Need to reschedule'},
  {id:'m75',month:'March 2025',date:'3/19',rep:'Tim',company:'Product Air',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Wants to look into his data'},
  {id:'m76',month:'March 2025',date:'3/19',rep:'Mike',company:'Intelligent Service',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$7,000',notes:'Next zoom 4/1, wants 1,000 records'},
  {id:'m77',month:'March 2025',date:'3/20',rep:'Tim',company:'Abend Services',zoom_type:'Follow-Up',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Renewal call, missed'},
  {id:'m78',month:'March 2025',date:'3/20',rep:'Andrew',company:'Benzel Pest Control',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Looking to do commercial, follow-up booked'},
  {id:'m79',month:'March 2025',date:'3/20',rep:'Dan',company:'Trafford',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$3,000',notes:'500 records'},
  {id:'m80',month:'March 2025',date:'3/20',rep:'Mike',company:'B&D Industries',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$3,500',notes:'500-1000 records'},
  {id:'m81',month:'March 2025',date:'3/23',rep:'Tim',company:'NOCO',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$30,000',notes:'2k records @ $15 per or 50 sat @ $650'},
  {id:'m82',month:'March 2025',date:'3/23',rep:'Dan',company:'DAXX',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'',notes:'10 appts a month'},
  {id:'m83',month:'March 2025',date:'3/24',rep:'Travis',company:'HomeX',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'EA talking with decision makers'},
  {id:'m84',month:'March 2025',date:'3/24',rep:'Travis',company:'Glass Doctor - Ohio',zoom_type:'2nd Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Invite not on calendar, resent'},
  {id:'m85',month:'March 2025',date:'3/24',rep:'Travis',company:'Valor Exterior Partners',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$30,000',notes:'Sending pricing for packages'},
  {id:'m86',month:'March 2025',date:'3/24',rep:'Dan',company:'Sky View Roofing',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$17,500',notes:'8-10 commercial, 20-30 residential'},
  {id:'m87',month:'March 2025',date:'3/24',rep:'Tim',company:'Reliant Plumbing',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$11,000',notes:'2k records @ $5.50 per'},
  {id:'m88',month:'March 2025',date:'3/25',rep:'Dan',company:'Nations Roof',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'',notes:'20-30 commercial, onboarding April 9'},
  {id:'m89',month:'March 2025',date:'3/25',rep:'Travis',company:'Tradewinds Heating and Cooling',zoom_type:'2nd Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Did not get on call'},
  {id:'m90',month:'March 2025',date:'3/25',rep:'Tim',company:'Pella Houston',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Interested in B2B, past customers, speed-to-lead'},
  {id:'m91',month:'March 2025',date:'3/25',rep:'Tim',company:'Hughston Homes',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Needs to be at $250 per lead'},
  {id:'m92',month:'March 2025',date:'3/25',rep:'Tim',company:'Lavin Media',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'500 live time leads per day to start'},
  {id:'m93',month:'March 2025',date:'3/26',rep:'Travis',company:'ADL Heating and Air',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$6,000',notes:'Couple thousand records, reach out Wednesday'},
  {id:'m94',month:'March 2025',date:'3/26',rep:'Tim',company:'Dental Practice Solutions',zoom_type:'1st Zoom',sat:'Sat',outcome:'Not Interested',deal_value:'',notes:'Thought we were inbound'},
  {id:'m95',month:'March 2025',date:'3/27',rep:'Dan',company:'Care Construction',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'m96',month:'March 2025',date:'3/27',rep:'Travis',company:'Flotilla Partners',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$6,000',notes:'Speaking with COO/CFO about 1k records'},
  {id:'m97',month:'March 2025',date:'3/27',rep:'Travis',company:'ProLift Garage Door',zoom_type:'2nd Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:'4/10 Friday @ 11AM CST'},
  {id:'m98',month:'March 2025',date:'3/27',rep:'Travis',company:'Rack Electric',zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'',notes:'Annual agreement discussion'},
  {id:'m99',month:'March 2025',date:'3/27',rep:'Travis',company:'Marketing Meeting',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Will start referring business'},
  {id:'m100',month:'March 2025',date:'3/27',rep:'Travis',company:"Smith's Plumbing, Heating and Cooling",zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:'Emergency pop up, rescheduling Monday'},
  {id:'m101',month:'March 2025',date:'3/27',rep:'Dan',company:'National Reliance Group',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$15,000',notes:'15 commercial appts, zoom April 7 onboarding'},
  {id:'m102',month:'March 2025',date:'3/30',rep:'Travis',company:'By The Book Plumbing Heating & Air',zoom_type:'2nd Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:'Rescheduling for tomorrow'},
  {id:'m103',month:'March 2025',date:'3/30',rep:'Travis',company:'Alpine Roofing Complete',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:'Call back in two weeks'},
  {id:'m104',month:'March 2025',date:'3/30',rep:'Travis',company:'San Diego Affordable Spay',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Voicemail + Text'},
  {id:'m105',month:'March 2025',date:'3/30',rep:'Travis',company:'Clear Pay Processing',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:'Rescheduling 3/31'},
  {id:'m106',month:'March 2025',date:'3/30',rep:'Dan',company:'Granger Medical',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'m107',month:'March 2025',date:'3/30',rep:'Dan',company:'Alpha Construction Group',zoom_type:'1st Zoom',sat:'Sat',outcome:'Not Interested',deal_value:'',notes:'Very small, wanted appts without paying'},
  {id:'m108',month:'March 2025',date:'3/30',rep:'Tim',company:'Product Air',zoom_type:'2nd Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:'Needs help pulling data to kick off'},
  {id:'m109',month:'March 2025',date:'3/30',rep:'Tim',company:'Total Air & Heat',zoom_type:'1st Zoom',sat:'Sat',outcome:'Not Interested',deal_value:'',notes:'Thought we were inbound'},
  {id:'m110',month:'March 2025',date:'3/31',rep:'Travis',company:'Turn Key Roofing',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$7,500',notes:'Speaking with CEO Leah, zoom 4/7'},
  {id:'m111',month:'March 2025',date:'3/31',rep:'Travis',company:'Apex Service Partners',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:'Regrouping with proper personnel'},
  {id:'m112',month:'March 2025',date:'3/31',rep:'Travis',company:"Smith's Plumbing, Heating and Cooling",zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Zoom 4/7 @ 1PM CST'},
  {id:'m113',month:'March 2025',date:'3/31',rep:'Travis',company:'Independent Home',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Went with AI outbound'},
  {id:'m114',month:'March 2025',date:'3/31',rep:'Dan',company:'Shelter Construction',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:''},
  {id:'m115',month:'March 2025',date:'3/31',rep:'Dan',company:'Glanz',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'',notes:'Only 2,500 records, thinks too expensive'},
  {id:'m116',month:'March 2025',date:'3/31',rep:'Tim',company:'Carrier',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$10,000',notes:'2 brands, 2k records each. Pending'},
  {id:'m117',month:'March 2025',date:'3/31',rep:'Ryan',company:'Clear The Air',zoom_type:'Follow-Up',sat:'Sat',outcome:'Proposal Sent',deal_value:'$4,125',notes:'12 month partner plan'},
  {id:'m118',month:'March 2025',date:'3/30',rep:'Travis',company:'Barbour Heating and Cooling',zoom_type:'Close Call',sat:'Sat',outcome:'Closed',deal_value:'$5,500',notes:'6 Month Plan'},
  {id:'m119',month:'March 2025',date:'3/19',rep:'Tim',company:'Palms Garage Doors',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Closed',deal_value:'$4,125',notes:'750 records @ $5.50'},
]

export const APRIL_DATA: Omit<ZoomEntry, 'created_at'>[] = [
  {id:'a1',month:'April 2025',date:'4/1',rep:'Travis',company:'Valor Exterior Partners',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Still budgeting, 4/8 @ 11AM CST'},
  {id:'a2',month:'April 2025',date:'4/1',rep:'Travis',company:'Great Lake Home Remodeling',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Did not get on Zoom'},
  {id:'a3',month:'April 2025',date:'4/1',rep:'Dan',company:'Iowa Ortho',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a4',month:'April 2025',date:'4/2',rep:'Dan',company:'Bartlett Roofing',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a5',month:'April 2025',date:'4/2',rep:'Travis',company:'Specialist Roofing',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$12,000+',notes:'Sending campaign agreement'},
  {id:'a6',month:'April 2025',date:'4/3',rep:'Travis',company:'Town and Country',zoom_type:'Close Call',sat:'Sat',outcome:'Proposal Sent',deal_value:'$8,250',notes:'1,500 Record Renewal'},
  {id:'a7',month:'April 2025',date:'4/3',rep:'Travis',company:'Liberty Service Partners',zoom_type:'1st Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Missed Zoom'},
  {id:'a8',month:'April 2025',date:'4/3',rep:'Travis',company:'Interior Plumbing & Heating',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:'Went out on boat, reschedule'},
  {id:'a9',month:'April 2025',date:'4/2',rep:'Mike',company:'Benzel Pest Control',zoom_type:'2nd Zoom',sat:'Missed',outcome:'Proposal Sent',deal_value:'',notes:''},
  {id:'a10',month:'April 2025',date:'4/3',rep:'Mike',company:'Caryl Mechanicals',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a11',month:'April 2025',date:'4/3',rep:'Mike',company:'Intelligent Service',zoom_type:'2nd Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a12',month:'April 2025',date:'4/1',rep:'Tim',company:'Rebel XL Studios',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$1,200',notes:'Waiting for form'},
  {id:'a13',month:'April 2025',date:'4/3',rep:'Tim',company:'Hudson Physicians',zoom_type:'Follow-Up',sat:'Sat',outcome:'Proposal Sent',deal_value:'$32,500',notes:'Waiting for form'},
  {id:'a14',month:'April 2025',date:'4/2',rep:'Ryan',company:'Arcitc Home Services',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$11,500',notes:'Waiting for form'},
  {id:'a15',month:'April 2025',date:'4/3',rep:'Ryan',company:'Blue Ridge Heating',zoom_type:'Follow-Up',sat:'Sat',outcome:'Proposal Sent',deal_value:'$11,000',notes:''},
  {id:'a16',month:'April 2025',date:'4/3',rep:'Ryan',company:'Air Titans',zoom_type:'Follow-Up',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Needs to train internal team'},
  {id:'a17',month:'April 2025',date:'4/6',rep:'Travis',company:'RowCal',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$20,000+',notes:'4/9 @ 1PM CST'},
  {id:'a18',month:'April 2025',date:'4/6',rep:'Dan',company:'Parkis Air',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'No Show',deal_value:'',notes:''},
  {id:'a19',month:'April 2025',date:'4/6',rep:'Mike',company:'Pure Plumbing & Air',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:''},
  {id:'a20',month:'April 2025',date:'4/7',rep:'Travis',company:'Turn Key Roofing',zoom_type:'2nd Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a21',month:'April 2025',date:'4/7',rep:'Travis',company:'Chillicothe Heating & Air',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'4/14 @ 10:30AM CST'},
  {id:'a22',month:'April 2025',date:'4/7',rep:'Travis',company:'First Quality Products',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a23',month:'April 2025',date:'4/7',rep:'Travis',company:"Smith's Plumbing",zoom_type:'2nd Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a24',month:'April 2025',date:'4/7',rep:'Dan',company:'National Roofing Group',zoom_type:'3rd Zoom',sat:'Rescheduled',outcome:'Proposal Sent',deal_value:'',notes:''},
  {id:'a25',month:'April 2025',date:'4/6',rep:'Tim',company:'Rooter Hero',zoom_type:'Follow-Up',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'$200,000',notes:'Annual deal in discussion'},
  {id:'a26',month:'April 2025',date:'4/6',rep:'Tim',company:"Hawk's Services",zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'$3,000',notes:'Annual Plan $36,000'},
  {id:'a27',month:'April 2025',date:'4/7',rep:'Dan',company:'Canyon Plumbing & Heating',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:''},
  {id:'a28',month:'April 2025',date:'4/8',rep:'Travis',company:'Omni Fiber',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'4/14 @ 12:30PM CST'},
  {id:'a29',month:'April 2025',date:'4/8',rep:'Travis',company:'Valor Exterior Partners',zoom_type:'3rd Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Trying to reschedule with Jake'},
  {id:'a30',month:'April 2025',date:'4/8',rep:'Travis',company:'Vertex Service Partners',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'4/15 @ 12PM CST'},
  {id:'a31',month:'April 2025',date:'4/8',rep:'Travis',company:'Ballard',zoom_type:'Follow-Up',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Did not get on Zoom'},
  {id:'a32',month:'April 2025',date:'4/9',rep:'Travis',company:'ABC',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'4/15 @ 10:30AM CST'},
  {id:'a33',month:'April 2025',date:'4/9',rep:'Travis',company:'RowCal',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Not a good fit'},
  {id:'a34',month:'April 2025',date:'4/9',rep:'Travis',company:'Gemini',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Meet at Nexstar event'},
  {id:'a35',month:'April 2025',date:'4/9',rep:'Travis',company:'Ballard',zoom_type:'Follow-Up',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a36',month:'April 2025',date:'4/9',rep:'Dan',company:'Total Appliance',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$8,000',notes:'Jotform sent'},
  {id:'a37',month:'April 2025',date:'4/9',rep:'Dan',company:'Addcox',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Next zoom next week'},
  {id:'a38',month:'April 2025',date:'4/10',rep:'Travis',company:'ProLift',zoom_type:'2nd Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:'Declined, waiting for response'},
  {id:'a39',month:'April 2025',date:'4/10',rep:'Dan',company:'Air & Water Solutions',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$3,000',notes:'500 records'},
  {id:'a40',month:'April 2025',date:'4/8',rep:'Tim',company:'Cotti-Johnson',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$6,000',notes:'1000 Records 12 months'},
  {id:'a41',month:'April 2025',date:'4/8',rep:'Tim',company:'Pinon Painting',zoom_type:'Follow-Up',sat:'Missed',outcome:'No Show',deal_value:'',notes:''},
  {id:'a42',month:'April 2025',date:'4/8',rep:'Tim',company:'Bonney',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:''},
  {id:'a43',month:'April 2025',date:'4/8',rep:'Tim',company:'Lavin Media',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'End of April follow up'},
  {id:'a44',month:'April 2025',date:'4/8',rep:'Tim',company:'Reliant',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$5,750',notes:'12 months, 1000 records'},
  {id:'a45',month:'April 2025',date:'4/9',rep:'Tim',company:'White River Mechanical',zoom_type:'Follow-Up',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Med device, chiropractor, follow up'},
  {id:'a46',month:'April 2025',date:'4/9',rep:'Tim',company:'Air Flo',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'They need to think it over'},
  {id:'a47',month:'April 2025',date:'4/9',rep:'Tim',company:'Capital City Garage',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Too small'},
  {id:'a48',month:'April 2025',date:'4/10',rep:'Tim',company:'Revel Garage',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Open estimate, 10 pack $250 per'},
  {id:'a49',month:'April 2025',date:'4/7',rep:'Ryan',company:'All American Plumbing',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:'Needs to be rescheduled'},
  {id:'a50',month:'April 2025',date:'4/10',rep:'Ryan',company:'Bright Green Roof',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Call Wednesday 4/15'},
  {id:'a51',month:'April 2025',date:'4/13',rep:'Dan',company:'Smart Window',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$6,000',notes:'Jotform sent'},
  {id:'a52',month:'April 2025',date:'4/14',rep:'Travis',company:'Chillicothe Heating & Air',zoom_type:'2nd Zoom',sat:'Rescheduled',outcome:'No Show',deal_value:'',notes:'4/16 @ 9AM CST'},
  {id:'a53',month:'April 2025',date:'4/14',rep:'Travis',company:'Omni Fiber',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'',notes:'Waiting for green light'},
  {id:'a54',month:'April 2025',date:'4/14',rep:'Travis',company:"Smith's Plumbing",zoom_type:'2nd Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Waiting for different time'},
  {id:'a55',month:'April 2025',date:'4/14',rep:'Travis',company:'HDL Capital',zoom_type:'1st Zoom',sat:'',outcome:'',deal_value:'',notes:''},
  {id:'a56',month:'April 2025',date:'4/14',rep:'Travis',company:'Free Agency',zoom_type:'1st Zoom',sat:'',outcome:'',deal_value:'',notes:''},
  {id:'a57',month:'April 2025',date:'4/14',rep:'Dan',company:'Infinity Home Services',zoom_type:'1st Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'',notes:'Kicking off with one brand'},
  {id:'a58',month:'April 2025',date:'4/14',rep:'Dan',company:'Parkis Air Care',zoom_type:'1st Zoom',sat:'Missed',outcome:'No Show',deal_value:'',notes:''},
  {id:'a59',month:'April 2025',date:'4/14',rep:'Dan',company:'Granger Medical',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a60',month:'April 2025',date:'4/15',rep:'Dan',company:'A-Team',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a61',month:'April 2025',date:'4/16',rep:'Travis',company:'Chillicothe Heating & Air',zoom_type:'2nd Zoom',sat:'Missed',outcome:'Follow-Up Needed',deal_value:'',notes:'Voicemail + Text'},
  {id:'a62',month:'April 2025',date:'4/16',rep:'Travis',company:'Aaron Overhead Doors',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'10,000 Records, Zoom next week'},
  {id:'a63',month:'April 2025',date:'4/16',rep:'Dan',company:'Bill Leary Air Conditioning',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'50000 records'},
  {id:'a64',month:'April 2025',date:'4/16',rep:'Dan',company:'GB Comfort Services',zoom_type:'1st Zoom',sat:'Rescheduled',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a65',month:'April 2025',date:'4/16',rep:'Dan',company:'Top Hat',zoom_type:'Follow-Up',sat:'Sat',outcome:'Closed',deal_value:'',notes:'1000 records to dial'},
  {id:'a66',month:'April 2025',date:'4/16',rep:'Dan',company:'Hydro-Flo',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:''},
  {id:'a67',month:'April 2025',date:'4/14',rep:'Tim',company:'Reliable Residential',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'Odd call'},
  {id:'a68',month:'April 2025',date:'4/14',rep:'Tim',company:'RBT',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'References'},
  {id:'a69',month:'April 2025',date:'4/17',rep:'Dan',company:'Lionheart',zoom_type:'1st Zoom',sat:'Sat',outcome:'Closed',deal_value:'$4,250',notes:'10 res & 1 comm'},
  {id:'a70',month:'April 2025',date:'4/15',rep:'Mike',company:'Caryl Mechanicals',zoom_type:'1st Zoom',sat:'Sat',outcome:'Follow-Up Needed',deal_value:'',notes:'2nd zoom scheduled'},
  {id:'a71',month:'April 2025',date:'4/16',rep:'Tim',company:'Product Air',zoom_type:'2nd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'',notes:'Call next week'},
  {id:'a72',month:'April 2025',date:'4/16',rep:'Tim',company:'Carrier',zoom_type:'3rd Zoom',sat:'Sat',outcome:'Proposal Sent',deal_value:'$12,000',notes:'Brands followup'},
]
